---
name: "Check versions"
permissions:
  contents: write
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: podman pull quay.io/fedora/fedora:42
      - run: podman run -d -v ./:/root/repo/ --init --name builder --network host quay.io/fedora/fedora:42 sleep 1h
      - run: podman exec builder dnf clean all
      - run: podman exec builder dnf update -y
      - run: podman exec builder dnf install -y gcc uv python3-devel python3-cffi python3-setuptools krb5-devel
      - run: podman exec --workdir /root/repo builder ./scripts/check_zfs.py
      - run: podman exec --workdir /root/repo builder ./scripts/check_kernels.py
      - run: podman stop builder
      - run: |
          git config user.name "Marcin Skarbek"
          git config user.email "1520395+mskarbek@users.noreply.github.com"
          git add versions/
          git commit -m "chore: update versions"
          git push
