---
name: OpenZFS repo
on:
  workflow_dispatch:
jobs:
  check-versions:
    strategy:
      matrix:
        os: [
            quay.io/fedora/fedora:41,
            #quay.io/fedora/fedora:42,
            #quay.io/fedora/fedora:43,
            #quay.io/fedora/fedora:rawhide,
            #quay.io/fedora/eln:latest,
            #quay.io/centos/centos:stream9,
            #quay.io/centos/centos:stream10,
          ]
        version: [2.2, 2.3, 2.4]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - id: meta
        run: |
          jq -r '.|"VERSION=\(.version)"' versions/openzfs-${{ matrix.version }}.json
          jq -r '.|"MAX_KERNEL_VERSION=\(.max_kernel_version)"' versions/openzfs-${{ matrix.version }}.json >> $GITHUB_ENV
          jq -r '.|"DOWNLOAD_URL=\(.dwonload_url)"' versions/openzfs-${{ matrix.version }}.json >> $GITHUB_ENV
          echo ${{ env.VERSION }}
          echo ${{ env.MAX_KERNEL_VERSION }}
          echo ${{ env.DOWNLOAD_URL }}
