---
name: OpenZFS repo
on:
  workflow_dispatch:
jobs:
  check-versions:
    strategy:
      matrix:
        os:
          [
            quay.io/fedora/fedora:41,
            quay.io/fedora/fedora:42,
            quay.io/fedora/fedora:rawhide,
            quay.io/fedora/eln:latest,
          ]
        version: [2.2, 2.3, 2.4]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - run: mkdir ./tmp
      - run: podman pull ${{ matrix.os }}
      - run: podman run -d -v ./tmp:/root/tmp --init --name builder --network host ${{ matrix.os }} sleep 1h
      - run: podman exec builder dnf clean all
      - run: podman exec builder dnf update -y
      - run: podman exec builder dnf install -y jq gcc make autoconf automake libtool rpm-build kernel-rpm-macros libtirpc-devel libblkid-devel libuuid-devel systemd systemd-devel openssl-devel zlib-ng-compat-devel libaio-devel libattr-devel libffi-devel libunwind-devel kernel-devel python3 python3-devel python3-cffi python3-setuptools openssl ncompress
      - run: podman exec --workdir /root builder curl -LO https://github.com/openzfs/zfs/releases/download/zfs-2.3.4/zfs-2.3.4.tar.gz
      - run: podman exec --workdir /root builder tar xvf zfs-2.3.4.tar.gz
      - run: podman exec --workdir /root/zfs-2.3.4 builder ./configure
      - run: podman exec --workdir /root/zfs-2.3.4 builder make -j1 rpm-utils
      - run: podman exec --workdir /root/zfs-2.3.4 builder mv -v *.rpm /root/tmp/
      - run: podman stop builder
